export * from "./src/Word.js";
export { default as Word } from "./src/Word.js";
export * from "./src/Definition.js";
export { default as Definition } from "./src/Definition.js";
export * from "./src/DefinitionList.js";
export { default as DefinitionList } from "./src/DefinitionList.js";
export * from "./src/Dictionary.js";
export { default as Dictionary } from "./src/Dictionary.js";
export * from "./src/Text.js";
export { default as Text } from "./src/Text.js";
